runtime: aspnetcore
env: flex

# These are set up in the circleci deploy process
# env_variables:
#     ASPNETCORE_DEPLOY_ENV: ${DEPLOY_ENV}
#     CUSTOMCONNSTR_postgres: Uid=${CLOUDSQL_USERNAME};Pwd=${CLOUDSQL_PASSWORD};Host=cloudsql;Database=dotnet-${DEPLOY_ENV}-visitors

# beta_settings:
#     cloud_sql_instances: ${CONNECTION_NAME}=tcp:5432

